# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NBCamp-TeamBoard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NBCamp-TeamBoard
  pod 'FlexLayout'
  pod 'PinLayout'

end
